import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Mohamed",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "Anna",
      email: "user@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Sport-Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Lacpste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "High quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 85,
      brand: "Nike",
      rating: 4.5,
      numReviews: 18,
      description: "High quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 89,
      countInStock: 56,
      brand: "Puma",
      rating: 4.3,
      numReviews: 65,
      description: "High quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 99,
      countInStock: 2,
      brand: "Adidas",
      rating: 5,
      numReviews: 120,
      description: "High quality product",
    },
  ],
};

export default data;
