const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descreption: "High quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      descreption: "High quality product",
    },
    {
      _id: "3",
      name: "Lacpste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      descreption: "High quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 85,
      brand: "Nike",
      rating: 4.5,
      numReviews: 18,
      descreption: "High quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 89,
      countInStock: 56,
      brand: "Puma",
      rating: 4.3,
      numReviews: 65,
      descreption: "High quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Shirt",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 99,
      countInStock: 2,
      brand: "Adidas",
      rating: 5,
      numReviews: 120,
      descreption: "High quality product",
    },
  ],
};

export default data;
